config/routes.rb
Rails.application.routes.draw do
  root "recipes#landing"

  resources "ingredients", only: [:index]
  resources "recipes", only: [:index] do
    get "check_ingredients", on: :collection
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
# frozen_string_literal: true

class Ingredient < ApplicationRecord
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients

  scope :filter_by_name, ->(name) { where("name ILIKE ?", "%#{name}%") }

  class << self
    def search(params)
      params[:name].present? ? filter_by_name(params[:name]) : all
    end
  end
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  SEARCHABLE_ATTRS = [:query]

  # Associations
  has_many :recipe_ingredients, dependent: :delete_all
  has_many :ingredients, through: :recipe_ingredients

  # Default scope to eager-load recipe ingredients.
  # RecipientIngredients are used in all the search, if not default_scope is not recommended
  default_scope { includes(:recipe_ingredients) }

  # Scopes
  scope :newest_by_ratings, -> { order(ratings: :desc, created_at: :desc) }
  scope :by_name, ->(query) { where("title ILIKE ?", "%#{query}%") }

  # Filters recipes by ingredients based on the provided ingredient_ids.
  # Retrieves recipes that include the specified ingredients.
  # The result includes recipes with at least one matching ingredient, ordered by matching percentage of ingredient_ids
  #
  # @param ingredient_ids [Array<Integer>] An array of ingredient IDs to filter recipes.
  #
  # @return [ActiveRecord::Relation] A collection of recipes that match the specified ingredients.
  # rubocop:disable Layout/LineLength
  scope :by_ingredients, ->(ingredient_ids = []) do
    joins(:ingredients)
      .where(ingredients: { id: ingredient_ids })
      .group("recipes.id")
      .select(
        "recipes.*, " \
        "(100.0 * SUM(CASE WHEN recipe_ingredients.ingredient_id IS NOT NULL THEN 1 ELSE 0 END) / (SELECT DISTINCT COUNT(*) FROM recipe_ingredients WHERE recipe_ingredients.recipe_id = recipes.id)) AS matching_percentage"
      )
      .order("matching_percentage DESC")
  end
  # rubocop:enable Layout/LineLength

  class << self
    # Search for recipes based on specified parameters. Can be extended easily adding new element to SEARCHABLE_ATTRS
    # and adding a new statement in the filters loop.
    #
    # @param [Hash] params - A hash of search parameters, valid keys on SEARCHABLE_ATTRS constant
    #   :query [String] - A search query for recipe titles
    #
    # @return [ActiveRecord::Relation] - A relation containing filtered and sorted recipes
    def search(params = {})
      filters = SEARCHABLE_ATTRS.filter { |attr| params[attr].present? }
      return newest_by_ratings if filters.empty?

      recipes = newest_by_ratings

      filters.each do |filter|
        case filter
        when :query then recipes = recipes.by_name(params[:query])
        end
      end

      recipes
    end
  end

  def matching_percentage(ingredient_ids)
    100.0 * (recipe_ingredients.map(&:ingredient_id) & ingredient_ids.map(&:to_i)).size / recipe_ingredients.size
  end
end

app/models/recipe_ingredient.rb
# frozen_string_literal: true

class RecipeIngredient < ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient, optional: true

  default_scope { includes(:ingredient) }

  def highlighted_description
    return description if ingredient_id.nil?

    
    description.gsub(/#{Regexp.quote(ingredient.name)}/i, "<strong>#{ingredient.name}</strong>")
               .gsub(' <strong>', "&nbsp<strong>") # fix spaces before and after the tag
               .gsub('</strong> ', "</strong>&nbsp") 
               .html_safe
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/concerns/paginable.rb
# frozen_string_literal: true

require "pagy/extras/countless"

module Paginable
  extend ActiveSupport::Concern

  # The default page size for paginated resources.
  PAGE_SIZE = 20

  included do
    include Pagy::Backend

    # Perform infinite scroll pagination on a collection of resources.
    #
    # This method uses the Pagy gem to paginate a collection of resources for
    # infinite scroll pagination. It returns a paginated subset of the
    # resources along with pagination metadata.
    # Aditionally sets the @pagination instance variable with the pagination metadata.
    #
    # @param resources [ActiveRecord::Relation] The collection of resources to paginate.
    # @param page_size [Integer] The number of items to include on each page.
    #   Defaults to `PAGE_SIZE` if not provided.
    #
    # @return [ActiveRecord::Relation] a paginated subset of the resources

    def infinite_scroll_pagination(resources, page_size: PAGE_SIZE)
      @pagination, paginated_resources = pagy_countless(
        resources, items: page_size
      )

      paginated_resources
    end
  end
end

app/controllers/ingredients_controller.rb
# frozen_string_literal: true

class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.search(params)

    respond_to do |format|
      format.turbo_stream
    end
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  include Paginable

  before_action :set_ingredients, only: :check_ingredients

  def landing
  end

  def index
    @recipes = infinite_scroll_pagination(
      Recipe.search(params),
    )

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def check_ingredients
    if params[:ingredient_ids]&.any?
      @recipes = infinite_scroll_pagination(
        Recipe.by_ingredients(params[:ingredient_ids]),
      )
    end

    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  private

  def set_ingredients
    @ingredients = Ingredient.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  include Pagy::Frontend
end

app/views/ingredients/index.turbo_stream.erb
<%= turbo_stream.update "ingredient_options" do %>
  <% @ingredients.each do |ingredient| %>
    <%= render "recipes/ingredient_option", ingredient: ingredient, checked: params[:ingredient_ids]&.include?(ingredient.id) %>
  <% end %>
<% end %>

app/views/layouts/_header.html.erb
<header class="text-gray-600 body-font bg-white">
  <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
    <%= link_to root_path, class: "flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" do %>
      <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-yellow-500 rounded-full" style="transform: rotate(-90deg);" viewBox="0 0 24 24">
        <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
      </svg>
      <span class="ml-3 text-xl">Recipe Finder</span>
    <% end %>
    <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
      <%= link_to "Search for recipes", recipes_path, class: "mr-5 hover:text-yellow-500" %>
      <%= link_to "Check your ingredients", check_ingredients_recipes_path, class: "mr-5 hover:text-yellow-500" %>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PennylaneAssignment</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-yellow-50 bg-opacity-50">
    <%= render 'layouts/header' %>
    <main class="container mx-auto mt-10 px-5 flex w-full">
      <%= yield %>
    </main>
  </body>
</html>

app/views/recipes/_infinite_scroll_frame.html.erb
<%- src_path = recipes_path(query: query, page: page, format: :turbo_stream) if action_name == "index" %>
<%- src_path = check_ingredients_recipes_path(ingredient_ids: ingredient_ids, page: page, format: :turbo_stream) if action_name == "check_ingredients" %>

<%= turbo_frame_tag "infinite_scroll", src: src_path, loading: :lazy %>

app/views/recipes/_ingredient_option.html.erb
<div class="relative flex items-start">
  <div class="flex h-6 items-center">
    <%= check_box_tag "ingredient_ids[]",
      ingredient.id,
      checked || false,
      id: "ingredient_id_#{ingredient.id}",
      data: { action: "change->searchable-dropdown#select", searchable_dropdown_target: "option" },
      class: "h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-600" %>
  </div>
  <div class="ml-3 text-sm leading-6">
    <%= label_tag "ingredient_id_#{ingredient.id}", ingredient.name.capitalize, class: "font-medium text-gray-900" %>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<li id="<%= dom_id(recipe) %>" class="bg-white rounded-xl overflow-hidden shadow-lg">
  <img class="h-48 w-full object-cover" src="<%= recipe.image %>" alt="Recipe Image">
  <div class="p-8">
    <h2 class="text-xl font-semibold text-gray-800 text-center"><%= recipe.title %></h2>
    <div class="grid grid-cols-2 gap-4">
      <div class="mt-2 ">
        <div class="mt-2 flex items-center text-sm text-gray-500">
          <span class="mr-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline" viewBox="0 0 25 25" fill="currentColor">
              <path xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12ZM12.4999 11.7929V6.96997C12.4999 6.69383 12.2761 6.46997 11.9999 6.46997C11.7238 6.46997 11.4999 6.69383 11.4999 6.96997V11.97C11.4999 11.975 11.5 11.9801 11.5002 11.9851C11.4962 12.118 11.545 12.2521 11.6464 12.3535L14.4748 15.1819C14.6701 15.3772 14.9867 15.3772 15.1819 15.1819C15.3772 14.9867 15.3772 14.6701 15.1819 14.4748L12.4999 11.7929Z" fill="#000000"/>
            </svg>
          </span>
          <span>Cook Time: <%= recipe.cook_time %> mins</span>
        </div>
        <div class="mt-2 flex items-center text-sm text-gray-500">
          <span class="mr-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 inline" viewBox="0 0 25 25" fill="currentColor">
              <path xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" d="M21 12C21 16.9706 16.9706 21 12 21C7.02944 21 3 16.9706 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12ZM12.4999 11.7929V6.96997C12.4999 6.69383 12.2761 6.46997 11.9999 6.46997C11.7238 6.46997 11.4999 6.69383 11.4999 6.96997V11.97C11.4999 11.975 11.5 11.9801 11.5002 11.9851C11.4962 12.118 11.545 12.2521 11.6464 12.3535L14.4748 15.1819C14.6701 15.3772 14.9867 15.3772 15.1819 15.1819C15.3772 14.9867 15.3772 14.6701 15.1819 14.4748L12.4999 11.7929Z" fill="#000000"/>
            </svg>
          </span>
          <span>Prep Time: <%= recipe.prep_time %> mins</span>
        </div>
        <div class="mt-2 flex items-center text-sm text-gray-500">
          <span class="mr-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" viewBox="0 0 30 30" fill="black">
              <path xmlns="http://www.w3.org/2000/svg" d="M29.3,12.7c-0.1-0.4-0.5-0.7-1-0.7h-8.7L17,3.7c-0.1-0.4-0.5-0.7-1-0.7s-0.8,0.3-1,0.7L12.4,12H3.7c-0.4,0-0.8,0.3-1,0.7  c-0.1,0.4,0,0.9,0.4,1.1l7,5.1l-2.7,8.3c-0.1,0.4,0,0.9,0.4,1.1c0.4,0.3,0.8,0.3,1.2,0l7-5.1l7,5.1c0.2,0.1,0.4,0.2,0.6,0.2  s0.4-0.1,0.6-0.2c0.4-0.3,0.5-0.7,0.4-1.1l-2.7-8.3l7-5.1C29.2,13.6,29.4,13.1,29.3,12.7z"/>            </svg>
          </span>
          <span>Ratings: <%= recipe.ratings %></span>
        </div>
        <div class="mt-2 flex items-center text-sm text-gray-500">
          <span class="mr-2">
            <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:serif="http://www.serif.com/" fill="#000000" class="h-5 w-5" viewBox="0 0 25 25" version="1.1" xml:space="preserve" style="fill-rule:evenodd;clip-rule:evenodd;stroke-linejoin:round;stroke-miterlimit:2;margin-left:4px;margin-top:3px;margin-right:-4px;">
              <g xmlns="http://www.w3.org/2000/svg" id="Page-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g id="Dribbble-Light-Preview" transform="translate(-220.000000, -2959.000000)" fill="#000000"><g id="icons" transform="translate(56.000000, 160.000000)"><path d="M167.812,2804.813 L169.812,2804.813 L169.812,2802.813 L167.812,2802.813 L167.812,2804.813 Z M183.381,2809.896 L183.381,2809.896 L172.485,2799 L164,2799 L164,2807.485 C166.428,2809.914 173.045,2816.53 175.515,2819 C178.609,2815.906 181.057,2813.458 184,2810.515 L183.381,2809.896 Z" id="tag_fill-[#1175]"></path></g></g></g>
            </svg>
          </span>
          <span>Category: <%= recipe.category %></span>
        </div>
        <div class="mt-2 flex items-center text-sm text-gray-500">
          <span class="mr-2">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 inline" viewBox="0 0 25 25" fill="currentColor">
              <path xmlns="http://www.w3.org/2000/svg" d="M17.0671 2.27157C17.5 2.09228 17.9639 2 18.4324 2C18.9009 2 19.3648 2.09228 19.7977 2.27157C20.2305 2.45086 20.6238 2.71365 20.9551 3.04493C21.2864 3.37621 21.5492 3.7695 21.7285 4.20235C21.9077 4.63519 22 5.09911 22 5.56761C22 6.03611 21.9077 6.50003 21.7285 6.93288C21.5492 7.36572 21.2864 7.75901 20.9551 8.09029L20.4369 8.60845L15.3916 3.56308L15.9097 3.04493C16.241 2.71365 16.6343 2.45086 17.0671 2.27157Z" fill="#000000"/>
              <path xmlns="http://www.w3.org/2000/svg" d="M13.9774 4.9773L3.6546 15.3001C3.53154 15.4231 3.44273 15.5762 3.39694 15.7441L2.03526 20.7369C1.94084 21.0831 2.03917 21.4534 2.29292 21.7071C2.54667 21.9609 2.91693 22.0592 3.26314 21.9648L8.25597 20.6031C8.42387 20.5573 8.57691 20.4685 8.69996 20.3454L19.0227 10.0227L13.9774 4.9773Z" fill="#000000"/>
            </svg>
          </span>
          <span>Author: <%= recipe.author %></span>
        </div>
      </div>
      <div class="mt-2 flex items-start text-sm text-gray-500">
        <span class="mt-2 mr-2">
          <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Uploaded to svgrepo.com" class="h-5 w-5" viewBox="0 0 32 32" xml:space="preserve"><style type="text/css">.puchipuchi_een{fill:#111918;}</style>
            <path class="puchipuchi_een" d="M32,13c0,0.552-0.447,1-1,1h-1.697L27,15.535V28c0,0.55-0.45,1-1,1H6c-0.55,0-1-0.45-1-1V15.535  L2.697,14H1c-0.553,0-1-0.448-1-1s0.447-1,1-1h2c0.197,0,0.391,0.059,0.555,0.168L5,13h22l1.445-0.832  C28.609,12.059,28.803,12,29,12h2C31.553,12,32,12.448,32,13z M5,11c0,0,0,0,0-1c0-0.79,2.503-2.199,7-2.759V6c0-1.299,1.03-2,2-2h4  c0.97,0,2,0.701,2,2v1.241c4.497,0.56,7,1.969,7,2.759c0,1,0,1,0,1c0,0.55-0.45,1-1,1H6C5.45,12,5,11.55,5,11z M14,7.062  C14.639,7.025,15.3,7,16,7s1.361,0.025,2,0.062V6h-4V7.062z"/>
          </svg>
        </span>
        <ul class="mt-2 text-sm text-gray-500 pl-5 space-y-1 list-inside">
          <% recipe.recipe_ingredients.each do |ingredient| %>
            <%= render "recipes/recipe_ingredient", ingredient: ingredient, check_matched_ingredients: check_matched_ingredients %>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</li>

app/views/recipes/_recipe_ingredient.html.erb
<li class="flex items-start">
  <%- if check_matched_ingredients %>
    <% matched = ingredient.ingredient_id.in?(params[:ingredient_ids].map(&:to_i)) %>
    <% text_color = matched ? 'text-green-500' : '' %>
    <% description = matched ? ingredient.highlighted_description : ingredient.description %>

    <svg class="w-3.5 h-3.5 mr-2 flex-shrink-0 <%= text_color %>" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
      <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
    </svg>
    <span><%= description %></span>
  <% else %>
    <span><%= ingredient.description %></span>
  <% end %>
</li>

app/views/recipes/_recipes.html.erb
<%= render partial: "recipes/recipe", collection: recipes, locals: { check_matched_ingredients: check_matched_ingredients } %>

app/views/recipes/_search_form.html.erb
<div class="p-4 py-8 bg-gray-100">
  <%= form_with(url: recipes_path, method: "GET", class: "w-full", data: { controller: "autosubmit" }) do |form| %>
    <div class="flex justify-center">
      <%= form.text_field :query, 
          class: "relative m-0 block w-full flex-auto rounded border border-solid border-neutral-300 bg-white px-3 py-[0.25rem] text-gray-700",
          value: params[:query],
          placeholder: "Search for your recipe",
          data: { action: "input->autosubmit#debouncedSubmit" }
      %>
    </div>
  <% end %>
</div>

app/views/recipes/_searchable_dropdown.html.erb
<%= form_tag check_ingredients_recipes_path, method: :get, class: "mb-20" do %>
  <div data-controller="dropdown">
    <%= label_tag :ingredients, "Ingredients", class: "block text-sm font-medium leading-6 text-gray-900" %>
    <div class="relative mt-2">
      <button type="button" data-action="click->dropdown#toggle click@window->dropdown#hide" class="relative w-full cursor-default rounded-md bg-white py-1.5 pl-3 pr-10 text-left text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 focus:outline-none focus:ring-2 focus:ring-indigo-600 sm:text-sm sm:leading-6" aria-haspopup="listbox" aria-expanded="true" aria-labelledby="listbox-label">
        <span class="block truncate">Select the ingredients you have</span>
        <span class="pointer-events-none absolute inset-y-0 right-0 flex items-center pr-2">
          <svg class="h-5 w-5 text-gray-400" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M10 3a.75.75 0 01.55.24l3.25 3.5a.75.75 0 11-1.1 1.02L10 4.852 7.3 7.76a.75.75 0 01-1.1-1.02l3.25-3.5A.75.75 0 0110 3zm-3.76 9.2a.75.75 0 011.06.04l2.7 2.908 2.7-2.908a.75.75 0 111.1 1.02l-3.25 3.5a.75.75 0 01-1.1 0l-3.25-3.5a.75.75 0 01.04-1.06z" clip-rule="evenodd" />
          </svg>
        </span>
      </button>

      <div
        data-dropdown-target="menu"
        data-controller="searchable-dropdown"
        data-searchable-dropdown-url-value="<%= ingredients_path %>"
        data-searchable-dropdown-attribute-value="name"
        class="hidden absolute p-6 z-10 mt-1 max-h-60 w-full overflow-auto rounded-md bg-white text-base shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none sm:text-sm">
        <input
          type="text"
          name="ingredient_name"
          data-action="searchable-dropdown#debouncedChange"
          data-searchable-dropdown-target="search"
          class="block w-full rounded-md border-0 py-1.5 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm sm:leading-6" placeholder="Mozzarella">  
        
          <button
            data-searchable-dropdown-target="reset"
            data-action="searchable-dropdown#resetSelection"
            class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold w-full py-1 px-4 mb-6 mt-2 rounded inline-flex items-center">
            <span>Reset Ingredients</span>
            <svg class="fill-current w-4 h-4 mr-2 " xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path xmlns="http://www.w3.org/2000/svg" d="M6.99486 7.00636C6.60433 7.39689 6.60433 8.03005 6.99486 8.42058L10.58 12.0057L6.99486 15.5909C6.60433 15.9814 6.60433 16.6146 6.99486 17.0051C7.38538 17.3956 8.01855 17.3956 8.40907 17.0051L11.9942 13.4199L15.5794 17.0051C15.9699 17.3956 16.6031 17.3956 16.9936 17.0051C17.3841 16.6146 17.3841 15.9814 16.9936 15.5909L13.4084 12.0057L16.9936 8.42059C17.3841 8.03007 17.3841 7.3969 16.9936 7.00638C16.603 6.61585 15.9699 6.61585 15.5794 7.00638L11.9942 10.5915L8.40907 7.00636C8.01855 6.61584 7.38538 6.61584 6.99486 7.00636Z" fill="#0F0F0F"/></svg>
          </button>

        <div class="space-y-3" id="ingredient_options">
          <% @ingredients.each do |ingredient| %>
            <%= render "recipes/ingredient_option", ingredient: ingredient, selected_ingredients: selected_ingredients, checked: ingredient.id.to_s.in?(selected_ingredients) %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= submit_tag "Apply changes", class: "bg-yellow-500 hover:bg-yellow-400 text-gray-800 font-bold w-full py-1 px-4 mt-2 rounded items-center" %>
<% end %>

app/views/recipes/check_ingredients.html.erb
<%= render 'recipes/searchable_dropdown', selected_ingredients: (params[:ingredient_ids] || []) %>

<div class="mx-auto w-full px-4 pt-5">
  <div class="mx-auto mt-5">
    <ul id="recipes" role="list" class="grid grid-cols-2 gap-4">
      <%- if @recipes %>
        <%= render "recipes/recipes", recipes: @recipes, check_matched_ingredients: true %>
      <% else %>
        Add ingredients to find recipes that match your fridge
      <% end%>
    </ul>
    <%- if @pagination&.next.present? %>
      <%= render 'recipes/infinite_scroll_frame', page: 2, ingredient_ids: (params[:ingredient_ids] || []) %>
    <% end %>
  </div>
</div>

app/views/recipes/check_ingredients.turbo_stream.erb
<%= turbo_stream.append "recipes", partial: "recipes/recipes", locals: { recipes: @recipes, check_matched_ingredients: true } %>

<% if @pagination.next.present? %>
  <%= turbo_stream.replace "infinite_scroll",
    partial: "recipes/infinite_scroll_frame",
    locals: { 
      page: @pagination.next,
      ingredient_ids: (params[:ingredient_ids] || [])
    }
  %>
<% end %>

app/views/recipes/index.html.erb
<div class="mx-auto w-full px-4 pt-5">
  <%= render "recipes/search_form" %>
  <div class="mx-auto mt-5">
    <ul id="recipes" role="list" class="grid grid-cols-2 gap-4">
    </ul>
    <%= render 'recipes/infinite_scroll_frame', page: 1, query: params[:query] %>
  </div>
</div>

app/views/recipes/index.turbo_stream.erb
<%= turbo_stream.append "recipes", partial: "recipes/recipes", locals: { recipes: @recipes, check_matched_ingredients: false } %>
 
<% if @pagination.next.present? %>
  <%= turbo_stream.replace "infinite_scroll",
    partial: "recipes/infinite_scroll_frame",
    locals: { 
      page: @pagination.next,
      query: params[:query],
    }
  %>
<% end %>

app/views/recipes/landing.html.erb
<section class="text-gray-600 body-font w-full">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-col text-center w-full mb-10">
      <h1 class="sm:text-3xl text-2xl font-medium title-font mb-4 text-yellow-500">Recipe Finder</h1>
      <p class="w-2/3 mx-auto leading-relaxed text-lg">Your Culinary Journey Starts Here</p>
    </div>
    <div class="flex flex-wrap -m-4">
      <div class="w-1/2 p-4">
        <div class="bg-white rounded-lg border border-slate-300">
          <%= image_tag("recipes.png", class: "h-96 rounded w-full object-cover object-center mb-3") %>
          <div class="p-6 pt-3 text-center">
            <h2 class="tracking-widest text-yellow-500 text-lg font-medium title-font">Search for recipes</h2>
            <p class="pt-2 leading-relaxed text-base">Explore a wide range of recipes from around the world.<br>Find something new to try for dinner tonight.</p>
            <%= link_to "Get Started", recipes_path, class: "inline-block text-center text-white bg-yellow-500 rounded text-lg w-1/2 px-8 py-2 mt-8" %>
          </div>
        </div>
      </div>
      <div class="w-1/2 p-4 b-1">
        <div class="bg-white rounded-lg border border-slate-300">
          <%= image_tag("ingredients.png", class: "h-96 rounded w-full object-cover object-center mb-3") %>
          <div class="p-6 pt-3 text-center">
            <h2 class="tracking-widest text-yellow-500 text-lg font-medium title-font">Check Your Ingredients</h2>
            <p class="pt-2 leading-relaxed text-base">Wondering what to cook with the ingredients you have?<br>Let us suggest recipes based on what's in your fridge.</p>
            <%= link_to "Get Started", check_ingredients_recipes_path, class: "inline-block text-center text-white bg-yellow-500 rounded text-lg w-1/2 px-8 py-2 mt-8" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>